variables:
  # Agent VM image name
  vmImageName: 'ubuntu-22.04'
  # Root folder under which your composer.json file is available.
  rootFolder: $(System.DefaultWorkingDirectory)
  # PHP Version
  phpVersion: '8.3'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: BuildJob
        pool:
          vmImage: $(vmImageName)
        steps:
          - script: |
              sudo update-alternatives --set php /usr/bin/php$(phpVersion)
              sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
              sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
              sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
              sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
              php -version
            workingDirectory: $(rootFolder)
            displayName: 'Use PHP version $(phpVersion)'

          - script: composer install -o --no-interaction --prefer-dist
            workingDirectory: $(rootFolder)
            displayName: 'Composer install'

          - task: UseNode@1
            displayName: 'Use Node.js'
            inputs:
              version: '20.x'

          - script: npm install
            workingDirectory: $(rootFolder)
            displayName: 'NPM install'

          - script: npm run build
            workingDirectory: $(rootFolder)
            displayName: 'NPM Build'

          - script: |
              rm -rf $(rootFolder)/node_modules
              rm -rf $(rootFolder)/assets
              rm -rf $(rootFolder)/public/app/uploads
              rm -rf $(rootFolder)/.git
            displayName: 'Remove unused folder'

          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(rootFolder)'
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            displayName: 'Upload package'
            artifact: drop

  - stage: Deploy
    displayName: 'Deploy Web App'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeploymentJob
        pool: $(poolName)
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: 'Deploy Azure Web App'
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appName: $(webAppName)
                    appType: 'webAppLinux'
                    slotName: 'production'
                    resourceGroupName: $(resourceGroupName)
                    package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip