variables:
  # Agent VM image name
  vmImageName: 'ubuntu-22.04'
  # Root folder under which your composer.json file is available.
  rootFolder: $(System.DefaultWorkingDirectory)
  # PHP Version
  phpVersion: '8.4'

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: BuildJob
        pool:
          vmImage: $(vmImageName)
        steps:
          - script: |
              curl -sL https://github.com/shivammathur/spc/releases/latest/download/spc -o spc
              chmod +x spc
              sudo mv spc /usr/local/bin/
              spc --php-version "$(phpVersion)" \
              --coverage "pcov" \
              --extensions "mongodb, dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, sockets" \
              --tools "composer:v2"
            workingDirectory: $(rootFolder)
            displayName: 'Use PHP version $(phpVersion)'

          - script: composer install -o --no-interaction --prefer-dist
            workingDirectory: $(rootFolder)
            displayName: 'Composer install'

          - task: UseNode@1
            displayName: 'Use Node.js'
            inputs:
              version: '20.x'

          - script: npm install
            workingDirectory: $(rootFolder)
            displayName: 'NPM install'

          - script: npm run build
            workingDirectory: $(rootFolder)
            displayName: 'NPM Build'

          - script: |
              rm -rf $(rootFolder)/node_modules
              rm -rf $(rootFolder)/assets
              rm -rf $(rootFolder)/public/app/uploads
              rm -rf $(rootFolder)/.git
            displayName: 'Remove unused folder'

          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(rootFolder)'
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true

          - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            displayName: 'Upload package'
            artifact: drop

  - stage: Deploy
    displayName: 'Deploy Web App'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeploymentJob
        pool: $(poolName)
        environment: $(environmentName)
        strategy:
          runOnce:
            deploy:
              steps:
                #- script: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
                #  displayName: 'Install az cli'
                #- task: AzureCLI@2
                #  displayName: 'Switch WebApp to container mode'
                #  inputs:
                #    azureSubscription: $(azureSubscription)
                #    scriptType: bash
                #    scriptLocation: inlineScript
                #    inlineScript: |
                #      az webapp config container set \
                #        --resource-group $(resourceGroupName) \
                #        --name $(webAppName) \
                #        --container-image-name mcr.microsoft.com/appsvc/wordpress-debian-php:$(phpVersion)
                #      az webapp config appsettings set \
                #        --resource-group $(resourceGroupName) \
                #        --name $(webAppName) \
                #        --settings WEBSITES_ENABLE_APP_SERVICE_STORAGE=true
                #      az webapp restart -g $(resourceGroupName) -n $(webAppName)
                - task: AzureWebApp@1
                  displayName: 'Deploy Azure Web App'
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appName: $(webAppName)
                    appType: 'webAppLinux'
                    slotName: 'production'
                    resourceGroupName: $(resourceGroupName)
                    package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip