upstream php {
        server unix:/var/run/php/php-fpm.sock;
        #server 127.0.0.1:9000;
}

server {
        listen 80;
        ## Your website name goes here.
        server_name _;
        ## Your only path reference.
        root /home/site/wwwroot/public;
        ## This should be in your http block and if it is, it's not needed here.
        index index.php;

        location = /favicon.ico {
            log_not_found off;
            access_log off;
        }

        location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
        }

        location ~ /\. {
            deny all;
        }

        location ~* /(?:uploads|files)/.*\.php$ {
            deny all;
        }

        location ~ ^/api/(.*)?$ {
            rewrite ^/api/(.*)$ /edition/wp-admin/admin-ajax.php?action=$1&$args last;
        }

        # XMLRPC block starts here
        # Block XMLRPC requests to prevent DDoS attack
        location ~* /edition/xmlrpc\.php {
            error_page 405 /hostingstart_xmlrpc.html;
            return 405;
        }
        location = /hostingstart_xmlrpc.html {
            root /home/site/temp-root/;
            internal;
        }
        # XMLRPC block ends here

        # Disable sendfile as per https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
        sendfile off;
        set $skip_cache 1;

        location ~ ^/[_0-9a-zA-Z-]+/(edition|app|static|build)(.*)$ {
            try_files $uri $uri/ /$1$2$is_args$args;
        }

        location / {
            # This is cool because no php is touched for static content.
            # include the "?$args" part so non-default permalinks doesn't break when using query string
            try_files $uri $uri/ /index.php?$args;
        }

        location ~* \.php$ {
            #NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
            include fastcgi.conf;
            include fastcgi_params;
            fastcgi_intercept_errors on;
            fastcgi_pass php;

            fastcgi_read_timeout 300;
            fastcgi_cache_bypass $skip_cache;
            fastcgi_no_cache $skip_cache;
            fastcgi_cache off;
            fastcgi_cache_valid 60m;
        }

        location ~* \.(js|css|png|jpg|jpeg|webp|gif|ico|woff|woff2)$ {
            expires max;
            log_not_found off;
        }
}